# Generated by Django 3.0.2 on 2020-03-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendcard', '0002_auto_20200304_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendcard',
            old_name='content',
            new_name='nickname',
        ),
        migrations.AddField(
            model_name='friendcard',
            name='bio',
            field=models.TextField(default='', help_text='Write the content of your page here.'),
            preserve_default=False,
        ),
    ]
