# Generated by Django 3.0.2 on 2020-03-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendcard', '0003_auto_20200304_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendcard',
            name='gender',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
