# Generated by Django 3.0.2 on 2020-03-05 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendcard', '0005_friendcard_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendcard',
            name='author',
            field=models.ForeignKey(default='', help_text='The user that created this.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendcard',
            name='bio',
            field=models.TextField(help_text='Write the content of your bio here.'),
        ),
    ]
