# Generated by Django 3.0.2 on 2020-03-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendcard', '0006_auto_20200304_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendcard',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
